### ISSUE TITLE
error occurred

### ISSUE THREAD

**Issue by ForrestPi** [zhongwanjun/MemoryBank-SiliconFriend#5]
MemoryBank-SiliconFriend/SiliconFriend-ChatGLM-BELLE/../utils/prompt_utils.py", line 127, in build_prompt_with_search_memory_chatglm_app
    query = dialog['query']
TypeError: list indices must be integers or slices, not str

**Comment by ryuichi-sumida** [comment]
I have the same error...

**Comment by ryuichi-sumida** [comment]
If you change it to 

        query = dialog[0]
        response = dialog[1]

It should work!
