### ISSUE TITLE
How is the forget_memory.py used?

### ISSUE THREAD

**Issue by ryuichi-sumida** [zhongwanjun/MemoryBank-SiliconFriend#7]
I do not see in the code how forget_memory.py is used...
Any comment would help, thanks in advance!

Your work is amazing!! Thank you for this job!

**Comment by zhongwanjun** [comment]
Here is a option in activating it:

if data_args.enable_forget_mechanism:
    from memory_retrieval.forget_memory_new import LocalMemoryRetrieval
else:
    from memory_retrieval.local_doc_qa import LocalMemoryRetrieval

if activated, it will forget the memory according to the calculated ratio

**Comment by ryuichi-sumida** [comment]
Thank you for your quick response.

How often is the forgetting process applied? As of my knowledge, you didn't mention how often you applied the forgetting mechanism. I want to conduct an experiment to compare so any comment would be much appreciated!

**Comment by zhongwanjun** [comment]
We assume the forgetting mechanism should be activated every day of conversations. You can adjust it according to your needs! Thanks.

**Comment by ryuichi-sumida** [comment]
Got it thank you for your response!
